name: Deploy Pages Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Assets
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    permissions:
      id-token: write
      contents: read
    
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version-file: '.node-version'
        - name: Install Dependencies
          run: yarn install
        - name: Build
          run: yarn build
  
  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    needs: build

    permissions:
      id-token: write
      contents: write
    
    steps:
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist